### ISSUE TITLE
Hello Discord

### ISSUE THREAD

**Issue by benbenlaw** [bbl-team/Modpack-Support#1] opened 2024-04-07 19:25 UTC
### Modpack

None

### Version

all the versions

### Describe the bug

very buggy send help

### Steps to reproduce

1 make bug 

### Expected behaviour

no bug

### Screenshots

nah

### Additional information

nah

**Comment by benbenlaw** [comment] 2024-04-07 19:31
no ben you cant do this

**Comment by CharZinta** [comment] 2024-04-07 20:23
Ben is the coolest mod pack maker ever. This isn't a bug this is awesomeness

**Comment by CharZinta** [comment] 2024-04-07 20:24
The issue is closed and I will now learn at the feet of the master

**Comment by CharZinta** [comment] 2024-04-07 20:24
okay testing perms is fun lets really close it :)

**Closed as completed by CharZinta** 2024-04-07 20:24 UTC
Labels: Bug

**Comment by 901238746** [comment] 2024-12-02 02:04
bro
